### ISSUE TITLE
DenseClassifier errors on Colab

### ISSUE THREAD

**Issue by tantrev** [brendanhasz/probflow#1]
Hello!  I was super excited to discover this package because I'm a TFB newbie.  However, when I try to run it on Colab with one of my datasets, I run into these error messages:

https://pastebin.com/raw/f0dWt7U4

Here's an example Colab notebook with what I'm trying to do:
https://colab.research.google.com/drive/14B2vsG-WPID3YWo6gpXeCVy3K7Hk105Z
And here's the example data needed to upload to the notebook:
https://drive.google.com/file/d/1xJ-dOFrI8BJnoTXCT5c7RiL2HQk85yKj/view?usp=sharing

Any help would be more than appreciated.  Thank you in advance.

**Comment by tantrev** [comment]
Also, not sure if you've used Colab before, but you'll want to make sure the GPU is enabled in the Notebook by going to "Runtime" -> "Change runtime type" -> "Hardware accelerator" -> "GPU".

**Comment by brendanhasz** [comment]
Hi! Thanks for using ProbFlow, and sorry it doesn't work haha!  I hadn't tested the Dense layer too thoroughly and looks like there was bug.  I fixed it in https://github.com/brendanhasz/probflow/commit/177582007b2d8d3fa67e94377d5b75c1e684fa1a , which should hopefully fix the error you're getting (I can now run the colab you linked w/o error).

Oh and if you're running in colab, you may or may not have to do `--upgrade` when you run pip (seems like colab sometimes caches your pip downloads...).  I.e.:

```
pip install --upgrade git+http://github.com/brendanhasz/probflow.git
```

Lemme know if that fixes your problem or not, and thanks for letting me know about the issue!

**Comment by tantrev** [comment]
That did the trick!  Thank you for your help and making such a useful package.
