### ISSUE TITLE
NotImplementedError:...  issue when try to run SimpleLinearRegression example

### ISSUE THREAD

**Issue by caprone** [brendanhasz/probflow#66]
HI
"NotImplementedError: Cannot convert a symbolic Tensor (gradients/stateless_random_gamma/StatelessRandomGammaV2_grad/sub:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported"

this issue rises  when try to fit SimpleLinearRegression model...(the same example on doc ---> a simple 'copy and paste')

**Comment by brendanhasz** [comment]
Hi!  Thanks for posting the issue!  I'm assuming you're using the Tensorflow backend? 
 Sounds like this might be a problem with Tensorflow Probability not playing nice with newer Python versions (see https://github.com/tensorflow/probability/issues/1226).

Which Python version are you running, and which versions of `tensorflow` and `tesnsorflow-probability`?  Running the "Simple Linear Regression" example (I assume you mean [this one](https://probflow.readthedocs.io/en/latest/examples/linear_regression.html#simple-linear-regression)?) works with Python 3.7 and

```
tensorflow-probability==0.12.1 or 0.13.0
tensorflow==2.5.0
probflow==2.4.1
```

See [this colab](https://colab.research.google.com/drive/18IAhw98QmShUkLTRsD0j_9i1Xeq6W1bj?usp=sharing) for a working version.

So unfortunately you may have to downgrade your Python (to 3.8 or 3.7), and/or change tensorflow-probability versions (both 0.12.1 and 0.13.0 worked for me with Python 3.7).

**Comment by caprone** [comment]
HI and thanks
yes problem is Python 3.8
